package entity;
// Generated Aug 14, 2018 10:28:31 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;

/**
 * Nhanvien generated by hbm2java
 */
@Entity
@Table(name="nhanvien"
    ,catalog="demodb"
)
public class Nhanvien  implements java.io.Serializable {


     private Integer id;
     private Phongban phongban;
     private String name;
     private String gender;
     private String birthday;
     private String address;
     private String phone;
     private String email;
     private Integer luong;

    public Nhanvien(Integer id, Phongban phongban, String name, String gender, String birthday, String address, String phone, String email, Integer luong) {
        this.id = id;
        this.phongban = phongban;
        this.name = name;
        this.gender = gender;
        this.birthday = birthday;
        this.address = address;
        this.phone = phone;
        this.email = email;
        this.luong = luong;
    }

    public Nhanvien() {
    }

	
    public Nhanvien(Phongban phongban) {
        this.phongban = phongban;
    }
    public Nhanvien(Phongban phongban, String name, String gender, String birthday, String address, String phone, String email, Integer luong) {
       this.phongban = phongban;
       this.name = name;
       this.gender = gender;
       this.birthday = birthday;
       this.address = address;
       this.phone = phone;
       this.email = email;
       this.luong = luong;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="id", unique=true, nullable=false)
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="maphongban", nullable=false)
    public Phongban getPhongban() {
        return this.phongban;
    }
    
    public void setPhongban(Phongban phongban) {
        this.phongban = phongban;
    }

    
    @Column(name="name", length=100)
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }

    
    @Column(name="gender", length=3)
    public String getGender() {
        return this.gender;
    }
    
    public void setGender(String gender) {
        this.gender = gender;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="birthday", length=10)
    public String getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    
    @Column(name="address", length=100)
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }

    
    @Column(name="phone", length=11)
   
    public String getPhone() {
        return this.phone;
    }
    
    public void setPhone(String phone) {
        this.phone = phone;
    }

    
    @Column(name="email", length=100)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

    
    @Column(name="luong")
    public Integer getLuong() {
        return this.luong;
    }
    
    public void setLuong(Integer luong) {
        this.luong = luong;
    }




}


