package entity;
// Generated Aug 14, 2018 10:28:31 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Phongban generated by hbm2java
 */
@Entity
@Table(name="phongban"
    ,catalog="demodb"
)
public class Phongban  implements java.io.Serializable {


     private String maphong;
     private String tenphong;
     private Set<Nhanvien> nhanviens = new HashSet<Nhanvien>(9);
     private Integer sonv;
    public Phongban() {
    }
    @Column(name="sonv")
    public Integer getSonv() {
        return sonv;
    }

    public void setSonv(Integer sonv) {
        this.sonv = sonv;
    }

    public Phongban(String maphong, String tenphong, Integer sonv) {
        this.maphong = maphong;
        this.tenphong = tenphong;
        this.sonv = sonv;
    }

	
    public Phongban(String maphong) {
        this.maphong = maphong;
    }
    public Phongban(String maphong, String tenphong, Set<Nhanvien> nhanviens) {
       this.maphong = maphong;
       this.tenphong = tenphong;
       this.nhanviens = nhanviens;
    }

    public Phongban(String maphong, String tenphong) {
        this.maphong = maphong;
        this.tenphong = tenphong;
    }
   
     @Id 
     @GeneratedValue
    @Column(name="maphong", unique=true, nullable=false, length=2)
    public String getMaphong() {
        return this.maphong;
    }
    
    public void setMaphong(String maphong) {
        this.maphong = maphong;
    }

    
    @Column(name="tenphong", length=20)
    public String getTenphong() {
        return this.tenphong;
    }
    
    public void setTenphong(String tenphong) {
        this.tenphong = tenphong;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="phongban",cascade={CascadeType.ALL})
    public Set<Nhanvien> getNhanviens() {
        return this.nhanviens;
    }
    
    public void setNhanviens(Set<Nhanvien> nhanviens) {
        this.nhanviens = nhanviens;
    }




}


